# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseExample
# Add the Firebase pod for Google Analytics
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
pod 'FirebaseStorage'
pod 'Toast-Swift', '~> 5.0.0'
end
